data:
  target: idf.datasets.data_module.BaseDataModule
  params:
    train_config: configs/datasets/cbsd432_train_g15.yaml
    val_config: [configs/datasets/cbsd68_val_g15.yaml]

model:
  config: configs/models/sc2a_dkf.yaml
  resume: ~

lightning:
  seed: 0
  mode: fit
  matmul_precision: ~

  trainer:
    accelerator: auto
    precision: 32
    devices: [0]
    default_root_dir: runs/sc2a_dkf
    max_steps: 30000
    val_check_interval: 10000
    check_val_every_n_epoch: ~
    log_every_n_steps: 100
    gradient_clip_val: 0.1
    num_sanity_val_steps: 0
    enable_progress_bar: false

  callbacks:
    - target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        every_n_train_steps: 10000
        save_last: true
        filename: '{epoch}-{step}'
        verbose: true
    - target: pytorch_lightning.callbacks.LearningRateMonitor
      params:
        logging_interval: step

  loggers:
    - target: pytorch_lightning.loggers.CSVLogger
      params:
        save_dir: runs/sc2a_dkf
        name: CSVLogger
        version: sc2a_dkf
    - target: idf.models.loggers.LocalImageLogger
      params:
        save_dir: runs/sc2a_dkf
        name: LocalImageLogger
        version: sc2a_dkf

